/* Domain operations accept validated JSON-schema payloads with tool-specific shapes. */
/* eslint-disable @typescript-eslint/no-explicit-any */
export type JsonObject = Record<string, any>;
export type ShaderUniform = { name:string; value?:number; color?:string };
export type ThreeSceneNode = { id:string; kind:'sphere'|'box'|'torus'|'cylinder'|'cone'|'plane'|'icosahedron'; label:string; description?:string; position:[number,number,number]; scale?:[number,number,number]; rotation?:[number,number,number]; color?:string; emissive?:string; opacity?:number; roughness?:number; metalness?:number; material?:'standard'|'wireframe'; behavior?:'static'|'orbit'|'pulse'|'spin'|'float'; interaction?:'none'|'select'|'value'; speed?:number; phase?:number; orbitRadius?:number; value?:number; min?:number; max?:number; step?:number; unit?:string; weight?:number; shader?:{vertex?:string;fragment?:string;intensity?:number;uniforms?:ShaderUniform[]} };
export type ThreeExperienceSpec = { version:'1'; runtime:'threejs_webgl'; title:string; instructions:string; alt:string; camera:{position:[number,number,number];target:[number,number,number];fov?:number}; environment:{background:string;fogColor?:string;fogDensity?:number;ambientIntensity?:number}; nodes:ThreeSceneNode[]; connections?:Array<{id:string;from:string;to:string;color?:string;pulseSpeed?:number}>; outputNodeId?:string; mission?:{prompt:string;targetRange:[number,number];successMessage:string} };
export type LessonBlock = { id: string; kind: 'objective'|'paragraph'|'callout'|'worked_example'|'definition'|'steps'|'comparison'|'reflection'|'image'|'diagram'|'video'|'audio'|'answer'|'learning_canvas'|'interactive_experience'; title?: string; body?: string; data?: JsonObject };
export type QuizQuestion = { id:string; type:'single_choice'|'multiple_choice'|'numeric'|'ordering'; prompt:string; options?:string[]; correctAnswer:any; hint:string; explanation:string; maxAttempts:number; difficulty?:string };
export type Lesson = { id:string; title:string; summary:string; minutes:number; status:'not_started'|'active'|'completed'; blocks:LessonBlock[]; quiz:QuizQuestion[] };
export type Chapter = { id:string; title:string; lessonIds:string[] };
export type Course = { id:string; title:string; goal:string; level:string; timeBudgetMinutes:number; learningPreference:string; language:string; accessibilityPreferences:string[]; priorKnowledge:string; progress:number; status:'active'|'completed'|'archived'; activeLessonId:string; chapters:Chapter[]; lessons:Lesson[]; updatedAt:string };
export type LearnerRequest = { id:string; courseId:string; lessonId:string; blockId?:string; type:'question'|'teaching_preference'|'retry_request'; content:string; responseMode?:string; noteIds?:string[]; status:'pending'|'answered'; answer?:string; createdAt:string };
export type LanternState = {
  revision:number; learner:{id:string;name:string;preferences:string[]}; courses:Course[]; activeCourseId:string;
  location:{courseId?:string;chapterId?:string;lessonId?:string;blockId?:string;requestIdToReview?:string;adaptationId?:string};
  requests:LearnerRequest[]; notes:Array<{id:string;courseId:string;lessonId:string;blockId?:string;content:string;createdAt:string}>;
  attempts:Array<{id:string;courseId:string;lessonId:string;questionId:string;answer:any;correct:boolean;createdAt:string}>;
  adaptations:Array<{id:string;courseId:string;lessonId:string;signalIds:string[];reason:string;summary:string;operations:JsonObject[];status:'proposed'|'applied';createdAt:string}>;
  changes:Array<{id:string;courseId:string;summary:string;revision:number;beforeCourse:Course|null;createdAt:string;undone?:boolean}>;
  activity:Array<{id:string;courseId:string;lessonId?:string;type:string;summary:string;revision:number;createdAt:string}>; requestLedger:Record<string,JsonObject>;
};

const now = () => new Date().toISOString();
const clone = <T,>(value:T):T => JSON.parse(JSON.stringify(value));
const makeId = (prefix:string, requestId=crypto.randomUUID()) => `${prefix}_${requestId.replace(/[^a-zA-Z0-9]/g,'').slice(-12)}`;

const demoVertexShader = `uniform float uTime; varying vec3 vNormal; varying vec3 vPosition; void main(){ vNormal=normalize(normalMatrix*normal); vPosition=position; float wave=sin(position.y*4.0+uTime*1.8)*0.06; vec3 moved=position+normal*wave; gl_Position=projectionMatrix*modelViewMatrix*vec4(moved,1.0); }`;
const demoFragmentShader = `uniform float uTime; uniform vec3 uColor; uniform float uIntensity; varying vec3 vNormal; varying vec3 vPosition; void main(){ float fresnel=pow(1.0-abs(vNormal.z),2.0); float pulse=0.65+0.35*sin(uTime*2.4+vPosition.y*3.0); vec3 glow=uColor*(0.7+pulse*uIntensity)+vec3(0.15,0.35,1.0)*fresnel; gl_FragColor=vec4(glow,0.94); }`;

export function createNeuralGravityExperience():ThreeExperienceSpec {
  return {version:'1',runtime:'threejs_webgl',title:'Neural gravity well',instructions:'Orbit the world, select an evidence orb, and tune its value. Reach the green target band to clear the mission.',alt:'An interactive three-dimensional neural network world. Three evidence orbs orbit a glowing central neuron and connect to a prediction ring. Sliders change the evidence values and live predicted probability.',camera:{position:[0,2.4,8.6],target:[0,0,0],fov:42},environment:{background:'#050b18',fogColor:'#07152b',fogDensity:.034,ambientIntensity:1.35},outputNodeId:'output',mission:{prompt:'Balance the evidence to land the prediction inside the target field.',targetRange:[72,82],successMessage:'You stabilized the prediction.'},nodes:[
    {id:'sleep',kind:'sphere',label:'Sleep',description:'Rest contributes a steady baseline signal.',position:[-3,1.45,.2],scale:[.58,.58,.58],color:'#6f8cff',emissive:'#244acb',behavior:'float',interaction:'value',speed:.8,phase:.2,value:7,min:0,max:10,step:1,unit:'h',weight:.12},
    {id:'study',kind:'sphere',label:'Study',description:'Study time is the strongest adjustable signal.',position:[-3,-.05,.5],scale:[.7,.7,.7],color:'#ff6d63',emissive:'#8e241f',behavior:'pulse',interaction:'value',speed:1.2,phase:1.2,value:4,min:0,max:8,step:1,unit:'h',weight:.22},
    {id:'prior',kind:'sphere',label:'Prior score',description:'Prior knowledge nudges the prediction before new evidence arrives.',position:[-3,-1.55,-.15],scale:[.62,.62,.62],color:'#8aa2ff',emissive:'#2949ac',behavior:'float',interaction:'value',speed:.72,phase:2.4,value:82,min:0,max:100,step:1,unit:'%',weight:.012},
    {id:'neuron',kind:'icosahedron',label:'Evidence core',description:'The shader turns the mixed evidence into a living energy field.',position:[0,0,0],scale:[1.25,1.25,1.25],color:'#315eea',behavior:'spin',interaction:'select',speed:.8,shader:{vertex:demoVertexShader,fragment:demoFragmentShader,intensity:1.2}},
    {id:'orbit_a',kind:'torus',label:'Hidden layer orbit',position:[0,0,0],scale:[1.75,1.75,1.75],rotation:[1.57,0,.32],color:'#365eb5',opacity:.32,material:'wireframe',behavior:'spin',interaction:'none',speed:-.18},
    {id:'output',kind:'torus',label:'Prediction field',description:'The ring glows green when the probability reaches the mission target.',position:[3.15,0,0],scale:[1.05,1.05,1.05],rotation:[0,1.57,0],color:'#8da7ff',emissive:'#315eea',roughness:.18,metalness:.76,behavior:'pulse',interaction:'select',speed:.75},
  ],connections:[{id:'sleep_neuron',from:'sleep',to:'neuron',color:'#6f8cff',pulseSpeed:1},{id:'study_neuron',from:'study',to:'neuron',color:'#ff6d63',pulseSpeed:1.4},{id:'prior_neuron',from:'prior',to:'neuron',color:'#8aa2ff',pulseSpeed:.8},{id:'neuron_output',from:'neuron',to:'output',color:'#65d9a7',pulseSpeed:1.8}]};
}

export function createSeedState():LanternState {
  const courseId='course_neural_foundations', lessonId='lesson_prediction_shape';
  return { revision:12, learner:{id:'learner_demo',name:'Alex',preferences:['visual explanations','short practice loops']}, activeCourseId:courseId, location:{courseId,lessonId},
    courses:[{ id:courseId,title:'Neural networks, from first principles',goal:'Understand how neural networks learn without hiding behind jargon.',level:'beginner',timeBudgetMinutes:90,learningPreference:'visual explanations with concrete examples',language:'en',accessibilityPreferences:[],priorKnowledge:'basic algebra',progress:32,status:'active',activeLessonId:lessonId,updatedAt:now(),
      chapters:[{id:'chapter_patterns',title:'Finding the pattern',lessonIds:['lesson_model_learns',lessonId,'lesson_measuring_error','lesson_step_downhill']},{id:'chapter_training',title:'Learning in motion',lessonIds:['lesson_gradient','lesson_loop','lesson_overfit','lesson_next']}],
      lessons:[
        {id:'lesson_model_learns',title:'A model that learns',summary:'Meet the learning loop.',minutes:9,status:'completed',blocks:[{id:'block_intro',kind:'paragraph',body:'A model learns by making a prediction, measuring its error, and changing a little.'}],quiz:[]},
        {id:lessonId,title:'The shape of a prediction',summary:'Trace evidence through one neuron.',minutes:12,status:'active',blocks:[
          {id:'canvas_prediction',kind:'learning_canvas',title:'The shape of a prediction',data:{objective:'Trace evidence through a neuron, change its inputs, and explain what the output means.',model:'weighted_sum_probability',scenes:[
            {id:'scene_observe',title:'Meet the evidence',narration:'A prediction starts with clues. Here we have sleep, study time, and a prior score.',focus:'Observe',durationSeconds:22,transition:'fade',elements:[{id:'sleep',type:'slider',label:'Sleep',unit:'hours',min:0,max:10,value:7,weight:.22,color:'#4f7cff'},{id:'study',type:'slider',label:'Study time',unit:'hours',min:0,max:8,value:4,weight:.42,color:'#ff6d63'},{id:'prior',type:'slider',label:'Prior score',unit:'%',min:0,max:100,value:82,weight:.036,color:'#7f9dff'}]},
            {id:'scene_weight',title:'Turn influence up or down',narration:'A weight controls how loudly each clue speaks. A larger weight gives that input more influence.',focus:'Weight inputs',durationSeconds:28,transition:'slide',elements:[{id:'formula_weight',type:'formula',label:'input × weight = contribution'}]},
            {id:'scene_combine',title:'Mix the evidence',narration:'The neuron adds every weighted contribution into one evidence score.',focus:'Combine',durationSeconds:24,transition:'focus',elements:[{id:'callout_mix',type:'callout',label:'One score now represents all three clues.'}]},
            {id:'scene_predict',title:'Shape a probability',narration:'The mixed score passes through a smooth gate and becomes a probability between zero and one.',focus:'Predict',durationSeconds:26,transition:'reveal',elements:[{id:'formula_gate',type:'formula',label:'score → probability'}]},
            {id:'scene_check',title:'Explain the result',narration:'Change one clue in Try it, watch the prediction move, then explain which connection mattered most.',focus:'Check understanding',durationSeconds:20,transition:'fade',elements:[{id:'checkpoint_explain',type:'checkpoint',label:'Which input had the greatest influence?'}]}],transcriptCues:[
              {id:'cue_observe',sceneId:'scene_observe',speaker:'Lantern guide',timeLabel:'00:00',text:'A prediction starts with clues: sleep, study time, and a prior score.'},
              {id:'cue_weight',sceneId:'scene_weight',speaker:'Lantern guide',timeLabel:'00:22',text:'A weight controls how loudly each clue speaks.'},
              {id:'cue_combine',sceneId:'scene_combine',speaker:'Lantern guide',timeLabel:'00:50',text:'The neuron adds the weighted contributions into one evidence score.'},
              {id:'cue_predict',sceneId:'scene_predict',speaker:'Lantern guide',timeLabel:'01:14',text:'A smooth gate shapes the score into a probability.'},
              {id:'cue_check',sceneId:'scene_check',speaker:'Lantern guide',timeLabel:'01:40',text:'Now change one clue and explain what moved the prediction.'}],whiteboardPrompts:['Trace one signal from input to prediction.','Explain the neuron using your own metaphor.','Sketch what a larger weight changes.']}},
          {id:'experience_neural_gravity',kind:'interactive_experience',title:'Neural gravity well',data:createNeuralGravityExperience()},
          {id:'objective_trace',kind:'objective',body:'Trace one input through a neuron and explain what its output means.'},
          {id:'central_idea',kind:'paragraph',title:'A neuron is a tiny evidence mixer.',body:'It gives each input a different amount of influence, adds them together, then shapes the result into a prediction. The weights are simply the knobs that learning will adjust.'},
          {id:'diagram_prediction',kind:'diagram',title:'From signals to a prediction',data:{alt:'Three inputs—sleep, study time, and prior score—flow through weighted connections into a neuron that predicts a 78 percent chance of passing.',spec:{kind:'flow',nodes:[{id:'sleep',label:'Sleep · 7h'},{id:'study',label:'Study · 4h'},{id:'score',label:'Prior score · 82'},{id:'neuron',label:'Mix evidence'},{id:'prediction',label:'78% likely to pass'}],edges:[{from:'sleep',to:'neuron'},{from:'study',to:'neuron'},{from:'score',to:'neuron'},{from:'neuron',to:'prediction'}]}}},
          {id:'worked_weight',kind:'worked_example',title:'Try one weighted input',body:'A study-time input of 4 with weight 0.6 contributes 2.4 to the evidence total.'}],
          quiz:[{id:'quiz_weight',type:'single_choice',prompt:'What does a larger weight mean?',options:['The input has more influence','The model is more certain','The input is always correct'],correctAnswer:'The input has more influence',hint:'Think of weights as volume knobs for evidence.',explanation:'A larger weight makes that input contribute more strongly to the neuron’s total.',maxAttempts:2,difficulty:'foundation'}]},
        {id:'lesson_measuring_error',title:'Measuring error',summary:'Turn a miss into a useful signal.',minutes:11,status:'not_started',blocks:[],quiz:[]},
        {id:'lesson_step_downhill',title:'One step downhill',summary:'See how a weight changes.',minutes:14,status:'not_started',blocks:[],quiz:[]},
        {id:'lesson_gradient',title:'The direction of improvement',summary:'Read a gradient.',minutes:12,status:'not_started',blocks:[],quiz:[]},
        {id:'lesson_loop',title:'The training loop',summary:'Put the pieces together.',minutes:15,status:'not_started',blocks:[],quiz:[]},
        {id:'lesson_overfit',title:'When memory replaces learning',summary:'Recognize overfitting.',minutes:10,status:'not_started',blocks:[],quiz:[]},
        {id:'lesson_next',title:'Build your own tiny network',summary:'Apply the full model.',minutes:18,status:'not_started',blocks:[],quiz:[]}]}],
    requests:[],notes:[{id:'note_weights',courseId,lessonId,blockId:'central_idea',content:'Weights tell the neuron which clues to trust most.',createdAt:now()}],attempts:[],adaptations:[],changes:[],activity:[{id:'activity_seed',courseId,lessonId,type:'course_created',summary:'Course planned around visual explanations.',revision:12,createdAt:now()}],requestLedger:{} };
}

export function hydrateLanternState(state:LanternState):LanternState {
  const demo=state.courses.find(course=>course.id==='course_neural_foundations')?.lessons.find(lesson=>lesson.id==='lesson_prediction_shape');
  if(demo&&!demo.blocks.some(block=>block.kind==='interactive_experience'))demo.blocks.unshift({id:'experience_neural_gravity',kind:'interactive_experience',title:'Neural gravity well',data:createNeuralGravityExperience()});
  return state;
}

export const activeCourse=(state:LanternState)=>state.courses.find(c=>c.id===state.activeCourseId)??state.courses[0];
export const findCourse=(state:LanternState,id?:string)=>state.courses.find(c=>c.id===(id||state.activeCourseId));
export const findLesson=(course:Course|undefined,id?:string)=>course?.lessons.find(l=>l.id===(id||course.activeLessonId));

export function isSafePublicHttps(value:string){ try { const url=new URL(value); if(url.protocol!=='https:'||url.username||url.password)return false; const host=url.hostname.toLowerCase(); if(host==='localhost'||host.endsWith('.localhost')||host.endsWith('.local')||host==='0.0.0.0'||host==='::1')return false; if(/^127\./.test(host)||/^10\./.test(host)||/^192\.168\./.test(host)||/^169\.254\./.test(host))return false; const match=host.match(/^172\.(\d+)\./); return !(match&&Number(match[1])>=16&&Number(match[1])<=31); } catch{return false;} }
function validateShader(source:string|undefined){if(!source)return true;if(source.length>6000)return false;return !/(#include|#extension|\bwhile\s*\(|\bdo\s*\{|\bfor\s*\(|\bsampler\w*\b|\btexture\w*\s*\(|gl_FragDepth|discard)/.test(source);}
const fail=(code:string,summary:string)=>({ok:false,code,summary});
const success=(state:LanternState,summary:string,changed:JsonObject={},nextSuggestedTools?:string[])=>({ok:true,revision:state.revision,summary,...changed,...(nextSuggestedTools?{nextSuggestedTools}:{})});
function rememberChange(state:LanternState,beforeCourse:Course|null,courseId:string,summary:string){const id=makeId('change');state.changes.unshift({id,courseId,beforeCourse,summary,revision:state.revision,createdAt:now()});return id;}
function logActivity(state:LanternState,courseId:string,lessonId:string|undefined,type:string,summary:string){state.activity.unshift({id:makeId('activity'),courseId,lessonId,type,summary,revision:state.revision,createdAt:now()});state.activity=state.activity.slice(0,100);}
function insertBlock(lesson:Lesson,block:LessonBlock,afterBlockId?:string){const existing=lesson.blocks.findIndex(b=>b.id===block.id);if(existing>=0)lesson.blocks.splice(existing,1);if(afterBlockId){const index=lesson.blocks.findIndex(b=>b.id===afterBlockId);lesson.blocks.splice(index>=0?index+1:lesson.blocks.length,0,block);}else lesson.blocks.push(block);}
const lessonSummary=(item:Lesson)=>({id:item.id,title:item.title,summary:item.summary,minutes:item.minutes,status:item.status});
const courseSummary=(item:Course)=>({id:item.id,title:item.title,goal:item.goal,level:item.level,timeBudgetMinutes:item.timeBudgetMinutes,learningPreference:item.learningPreference,language:item.language,accessibilityPreferences:item.accessibilityPreferences,priorKnowledge:item.priorKnowledge,progress:item.progress,status:item.status,activeLessonId:item.activeLessonId,updatedAt:item.updatedAt});

export function readTool(state:LanternState,name:string,args:JsonObject){const course=findCourse(state,args.courseId),lesson=findLesson(course,args.lessonId);switch(name){
  case'get_lantern_capabilities':return{toolVersion:'1.2.0',schemaVersion:'2026-08',blockTypes:['objective','paragraph','callout','worked_example','definition','steps','comparison','reflection','learning_canvas','interactive_experience'],canvasModes:['3d_world','present','try','transcript','whiteboard','check'],canvasPrimitives:['text','node','connector','formula','callout','image','checkpoint','slider','choice'],interactiveRuntimes:['threejs_webgl'],scenePrimitives:['sphere','box','torus','cylinder','cone','plane','icosahedron'],interactionPrimitives:['select','value','orbit_camera','mission_target'],shaderSupport:{vertex:true,fragment:true,language:'GLSL',maxCharactersPerStage:6000,customUniforms:true},agentCodeExecution:false,sceneTransitions:['fade','slide','reveal','focus'],diagramKinds:['flow','hierarchy','timeline','cycle','comparison','number_line'],quizTypes:['single_choice','multiple_choice','numeric','ordering'],videoProviders:['youtube','vimeo'],audioProviders:['https'],mediaLimits:{maxBlocksPerLesson:80,maxCanvasScenes:12,maxCanvasElementsPerScene:30,maxThreeSceneNodes:64,maxThreeSceneConnections:120,maxDiagramNodes:40,maxTranscriptCharacters:50000},toolAvailability:'ready'};
  case'get_learning_context':return{learner:state.learner,revision:state.revision,activeCourse:course?{...course,lessons:args.includeLessonBlocks?course.lessons:course.lessons.map(lessonSummary)}:null,courseList:args.includeCourseList?state.courses.map(courseSummary):undefined,activeLesson:lesson,location:state.location,unresolvedRequests:state.requests.filter(r=>r.status==='pending')};
  case'get_learning_signals':return{revision:state.revision,notes:state.notes.filter(n=>(!args.courseId||n.courseId===args.courseId)&&(!args.lessonId||n.lessonId===args.lessonId)).slice(0,args.limit||50),attempts:state.attempts.filter(a=>(!args.courseId||a.courseId===args.courseId)&&(!args.lessonId||a.lessonId===args.lessonId)).slice(0,args.limit||50),progress:course?.progress??0,activity:state.activity.filter(a=>(!args.courseId||a.courseId===args.courseId)&&(!args.lessonId||a.lessonId===args.lessonId)&&(!args.sinceRevision||a.revision>args.sinceRevision)).slice(0,args.limit||50)};
  case'get_pending_learner_requests':return{revision:state.revision,requests:state.requests.filter(r=>r.status==='pending'&&(!args.courseId||r.courseId===args.courseId)&&(!args.lessonId||r.lessonId===args.lessonId)&&(!args.types?.length||args.types.includes(r.type))).slice(0,args.limit||50)};
  case'list_courses':return{revision:state.revision,courses:state.courses.filter(c=>!args.status||c.status===args.status).slice(0,args.limit||50).map(c=>({id:c.id,title:c.title,goal:c.goal,status:c.status,progress:c.progress,activeLessonId:c.activeLessonId,lastActivity:c.updatedAt}))};
  default:return fail('unsupported_tool',`Unknown read tool: ${name}`);
}}

export function mutateTool(current:LanternState,name:string,args:JsonObject):{state?:LanternState;result:JsonObject}{
  if(!args.requestId||typeof args.expectedRevision!=='number')return{result:fail('invalid_component_data','requestId and expectedRevision are required for mutations.')};
  if(current.requestLedger[args.requestId])return{result:current.requestLedger[args.requestId]};
  if(args.expectedRevision!==current.revision)return{result:fail('revision_conflict',`Expected revision ${args.expectedRevision}, but Lantern is at ${current.revision}. Read fresh context before retrying.`)};
  const state=clone(current);state.revision+=1;let result:JsonObject;let course=findCourse(state,args.courseId),lesson=findLesson(course,args.lessonId);const beforeCourse=course?clone(course):null;
  const noCourse=()=>!course?fail('course_not_found',`Course ${args.courseId||''} was not found.`):null;const noLesson=()=>!lesson?fail('lesson_not_found',`Lesson ${args.lessonId||''} was not found.`):null;
  switch(name){
    case'create_course':{const id=makeId('course',args.requestId);const created:Course={id,title:args.title,goal:args.goal,level:args.level,timeBudgetMinutes:args.timeBudgetMinutes,learningPreference:args.learningPreference,language:args.language||'en',accessibilityPreferences:args.accessibilityPreferences||[],priorKnowledge:args.priorKnowledge||'',progress:0,status:'active',activeLessonId:'',chapters:[],lessons:[],updatedAt:now()};state.courses.push(created);state.activeCourseId=id;state.location={courseId:id};const changeId=rememberChange(state,null,id,`Created ${created.title}`);logActivity(state,id,undefined,name,`Created course “${created.title}”.`);result=success(state,`Created course “${created.title}”.`,{courseId:id,changeId},['set_course_outline']);break;}
    case'update_course_settings':{if(noCourse())return{result:noCourse()!};for(const key of['goal','level','timeBudgetMinutes','learningPreference','language'])if(args[key]!==undefined)(course as any)[key]=args[key];course!.updatedAt=now();const changeId=rememberChange(state,beforeCourse,course!.id,args.reason);result=success(state,`Updated settings for “${course!.title}”.`,{courseId:course!.id,changeId});break;}
    case'set_course_outline':{if(noCourse())return{result:noCourse()!};const lessons:Lesson[]=[],chapters:Chapter[]=[];for(const chapter of args.chapters||[]){chapters.push({id:chapter.id,title:chapter.title,lessonIds:chapter.lessons.map((x:JsonObject)=>x.id)});for(const item of chapter.lessons){const old=course!.lessons.find(x=>x.id===item.id);lessons.push({id:item.id,title:item.title,summary:item.summary,minutes:item.minutes,status:old?.status||'not_started',blocks:old?.blocks||[],quiz:old?.quiz||[]});}}course!.chapters=chapters;course!.lessons=lessons;course!.activeLessonId=args.activeLessonId||lessons[0]?.id||'';if(lessons[0]&&!lessons.some(x=>x.status==='active'))lessons[0].status='active';state.location={courseId:course!.id,lessonId:course!.activeLessonId};const changeId=rememberChange(state,beforeCourse,course!.id,'Set course outline');result=success(state,`Planned ${lessons.length} lessons in ${chapters.length} chapters.`,{courseId:course!.id,lessonIds:lessons.map(x=>x.id),changeId},['upsert_lesson_blocks']);break;}
    case'upsert_lesson_blocks':{if(noCourse())return{result:noCourse()!};if(noLesson())return{result:noLesson()!};const blocks=(args.blocks||[])as LessonBlock[];if(blocks.some(b=>['image','diagram','video','audio'].includes(b.kind)))return{result:fail('invalid_component_data','Media blocks must use a strict attachment tool.')};lesson!.title=args.title;lesson!.summary=args.summary;if(args.mode==='replace')lesson!.blocks=blocks;else if(args.mode==='insert_after'){let after=args.afterBlockId;for(const block of blocks){insertBlock(lesson!,block,after);after=block.id;}}else lesson!.blocks.push(...blocks.filter(b=>!lesson!.blocks.some(old=>old.id===b.id)));const changeId=rememberChange(state,beforeCourse,course!.id,`Updated ${lesson!.title}`);result=success(state,`Updated ${blocks.length} lesson blocks.`,{courseId:course!.id,lessonId:lesson!.id,blockIds:blocks.map(b=>b.id),changeId});break;}
    case'set_lesson_learning_canvas':{if(noCourse())return{result:noCourse()!};if(noLesson())return{result:noLesson()!};const sceneIds=new Set((args.scenes||[]).map((scene:JsonObject)=>scene.id));if(sceneIds.size!==(args.scenes||[]).length)return{result:fail('invalid_component_data','Canvas scene identifiers must be unique.')};if((args.transcriptCues||[]).some((cue:JsonObject)=>!sceneIds.has(cue.sceneId)))return{result:fail('invalid_component_data','Every transcript cue must reference a scene in this canvas.')};const block:LessonBlock={id:args.id,kind:'learning_canvas',title:args.title,data:{objective:args.objective,model:args.model||'none',scenes:args.scenes,transcriptCues:args.transcriptCues||[],whiteboardPrompts:args.whiteboardPrompts||[]}};insertBlock(lesson!,block);const changeId=rememberChange(state,beforeCourse,course!.id,`Updated the learning canvas for ${lesson!.title}`);result=success(state,`Built a ${args.scenes.length}-scene learning canvas.`,{courseId:course!.id,lessonId:lesson!.id,blockId:block.id,sceneIds:[...sceneIds],changeId});break;}
    case'set_lesson_3d_experience':{if(noCourse())return{result:noCourse()!};if(noLesson())return{result:noLesson()!};const nodeIds=new Set((args.nodes||[]).map((node:JsonObject)=>node.id));if(nodeIds.size!==(args.nodes||[]).length)return{result:fail('invalid_component_data','Every 3D node needs a unique identifier.')};if((args.connections||[]).some((edge:JsonObject)=>!nodeIds.has(edge.from)||!nodeIds.has(edge.to)))return{result:fail('invalid_component_data','Every 3D connection must reference existing nodes.')};if(args.outputNodeId&&!nodeIds.has(args.outputNodeId))return{result:fail('invalid_component_data','The output node must exist in the 3D scene.')};if((args.nodes||[]).some((node:JsonObject)=>!validateShader(node.shader?.vertex)||!validateShader(node.shader?.fragment)))return{result:fail('unsafe_render_program','Shaders must be bounded, loop-free GLSL without texture access, extensions, includes, or depth writes.')};const data:ThreeExperienceSpec={version:'1',runtime:'threejs_webgl',title:args.title,instructions:args.instructions,alt:args.alt,camera:args.camera,environment:args.environment,nodes:args.nodes,connections:args.connections||[],outputNodeId:args.outputNodeId,mission:args.mission};const block:LessonBlock={id:args.id,kind:'interactive_experience',title:args.title,data};insertBlock(lesson!,block,args.afterBlockId);const changeId=rememberChange(state,beforeCourse,course!.id,`Built 3D world for ${lesson!.title}`);result=success(state,`Built the interactive 3D world “${args.title}” with ${args.nodes.length} objects.`,{courseId:course!.id,lessonId:lesson!.id,blockId:block.id,nodeIds:[...nodeIds],runtime:'threejs_webgl',changeId},['navigate_to_learning_item']);break;}
    case'remove_lesson_block':{if(noCourse())return{result:noCourse()!};if(noLesson())return{result:noLesson()!};const index=lesson!.blocks.findIndex(b=>b.id===args.blockId);if(index<0)return{result:fail('block_not_found',`Block ${args.blockId} was not found.`)};lesson!.blocks.splice(index,1);const changeId=rememberChange(state,beforeCourse,course!.id,args.reason);result=success(state,'Removed the lesson block.',{courseId:course!.id,lessonId:lesson!.id,blockId:args.blockId,changeId});break;}
    case'attach_lesson_image':case'attach_lesson_video':case'attach_lesson_audio':case'attach_lesson_diagram':{if(noCourse())return{result:noCourse()!};if(noLesson())return{result:noLesson()!};const kind=name.replace('attach_lesson_','')as'image'|'diagram'|'video'|'audio',url=args.url||args.imageUrl;if(url&&!isSafePublicHttps(url))return{result:fail('unsafe_media_url','Media must use a public HTTPS URL without credentials or private-network hosts.')};if(kind==='diagram'&&Boolean(args.imageUrl)===Boolean(args.spec))return{result:fail('invalid_component_data','Provide exactly one of imageUrl or a structured diagram spec.')};if(kind==='video'&&!['youtube','vimeo'].includes(args.provider))return{result:fail('unsupported_media_provider',`Video provider ${args.provider} is not supported.`)};if(kind==='audio'&&!String(args.transcript||'').trim())return{result:fail('invalid_component_data','Audio requires a complete transcript.')};const block:LessonBlock={id:args.id,kind,title:args.title,data:{...args}};delete block.data!.requestId;delete block.data!.expectedRevision;insertBlock(lesson!,block,args.afterBlockId);const changeId=rememberChange(state,beforeCourse,course!.id,`Attached ${kind}`);result=success(state,`Attached ${kind} “${args.title}”.`,{courseId:course!.id,lessonId:lesson!.id,blockId:block.id,changeId});break;}
    case'set_lesson_quiz':{if(noCourse())return{result:noCourse()!};if(noLesson())return{result:noLesson()!};lesson!.quiz=args.questions||[];const changeId=rememberChange(state,beforeCourse,course!.id,`Updated quiz for ${lesson!.title}`);result=success(state,`Set ${lesson!.quiz.length} quiz questions.`,{courseId:course!.id,lessonId:lesson!.id,questionIds:lesson!.quiz.map(q=>q.id),changeId});break;}
    case'answer_lesson_question':{const request=state.requests.find(r=>r.id===args.requestIdToAnswer);if(!request)return{result:fail('request_not_found',`Request ${args.requestIdToAnswer} was not found.`)};request.status='answered';request.answer=args.answer;course=findCourse(state,request.courseId);lesson=findLesson(course,request.lessonId);if(lesson)insertBlock(lesson,{id:makeId('answer',args.requestId),kind:'answer',title:'Answer from your teaching agent',body:args.answer,data:{requestId:request.id,miniQuiz:args.miniQuiz,challenge:args.challenge,recommendedFollowUp:args.recommendedFollowUp}},request.blockId);const changeId=rememberChange(state,beforeCourse,request.courseId,'Answered learner question');result=success(state,'Answered the learner question beside its anchor.',{requestIdAnswered:request.id,courseId:request.courseId,lessonId:request.lessonId,changeId});break;}
    case'save_learner_note':{if(noCourse())return{result:noCourse()!};if(noLesson())return{result:noLesson()!};const id=makeId('note',args.requestId);state.notes.unshift({id,courseId:course!.id,lessonId:lesson!.id,blockId:args.blockId,content:args.content,createdAt:now()});logActivity(state,course!.id,lesson!.id,name,'Saved a learner note.');result=success(state,'Saved the learner note.',{noteId:id,courseId:course!.id,lessonId:lesson!.id});break;}
    case'propose_learning_adaptation':{if(noCourse())return{result:noCourse()!};if(noLesson())return{result:noLesson()!};const id=makeId('adaptation',args.requestId);state.adaptations.unshift({id,courseId:course!.id,lessonId:lesson!.id,signalIds:args.signalIds,reason:args.reason,summary:args.summary,operations:args.operations,status:'proposed',createdAt:now()});result=success(state,'Created a reviewable learning adaptation.',{adaptationId:id,status:'proposed'},['apply_learning_adaptation']);break;}
    case'apply_learning_adaptation':{const adaptation=state.adaptations.find(a=>a.id===args.adaptationId);if(!adaptation)return{result:fail('request_not_found',`Adaptation ${args.adaptationId} was not found.`)};if(adaptation.status!=='proposed')return{result:fail('invalid_component_data','Only proposed adaptations can be applied.')};course=findCourse(state,adaptation.courseId);lesson=findLesson(course,adaptation.lessonId);if(!course||!lesson)return{result:fail('lesson_not_found','The adapted lesson no longer exists.')};const snapshot=clone(course);for(const op of adaptation.operations){if(op.type==='insert_block'&&op.block)insertBlock(lesson,op.block,op.afterBlockId);if(op.type==='update_block'&&op.block)insertBlock(lesson,op.block);if(op.type==='remove_block')lesson.blocks=lesson.blocks.filter(b=>b.id!==op.blockId);if(op.type==='update_lesson'){if(op.title)lesson.title=op.title;if(op.summary)lesson.summary=op.summary;}if(op.type==='set_quiz')lesson.quiz=op.questions||[];if(op.type==='add_media'&&op.block)insertBlock(lesson,op.block,op.afterBlockId);}adaptation.status='applied';const changeId=rememberChange(state,snapshot,course.id,adaptation.summary);result=success(state,`Applied adaptation: ${adaptation.summary}`,{adaptationId:adaptation.id,undoChangeId:changeId,lessonId:lesson.id});break;}
    case'undo_agent_change':{const change=state.changes.find(c=>c.id===args.changeId);if(!change)return{result:fail('request_not_found',`Change ${args.changeId} was not found.`)};if(change.undone||current.revision!==change.revision)return{result:fail('revision_conflict','This change cannot be undone across incompatible later revisions. Read fresh context and review the newer changes.')};if(change.beforeCourse){const index=state.courses.findIndex(c=>c.id===change.courseId);if(index>=0)state.courses[index]=change.beforeCourse;}else state.courses=state.courses.filter(c=>c.id!==change.courseId);change.undone=true;result=success(state,`Undid change: ${change.summary}`,{changeId:change.id,courseId:change.courseId});break;}
    case'set_lesson_progress':{if(noCourse())return{result:noCourse()!};if(noLesson())return{result:noLesson()!};lesson!.status=args.status;course!.progress=Math.max(0,Math.min(100,args.courseProgress));course!.updatedAt=now();result=success(state,`Marked “${lesson!.title}” ${args.status.replace('_',' ')}.`,{courseId:course!.id,lessonId:lesson!.id,status:lesson!.status,courseProgress:course!.progress});break;}
    case'navigate_to_learning_item':{const keys=['courseId','chapterId','lessonId','blockId','requestIdToReview','adaptationId'].filter(k=>args[k]);if(keys.length!==1)return{result:fail('invalid_component_data','Navigation requires exactly one semantic target.')};const key=keys[0];state.location={[key]:args[key]};if(key==='courseId')state.activeCourseId=args.courseId;if(key==='lessonId'){const owner=state.courses.find(c=>c.lessons.some(l=>l.id===args.lessonId));if(!owner)return{result:fail('lesson_not_found',`Lesson ${args.lessonId} was not found.`)};state.activeCourseId=owner.id;owner.activeLessonId=args.lessonId;state.location.courseId=owner.id;}result=success(state,`Navigated to ${key} ${args[key]}.`,{location:state.location});break;}
    default:return{result:fail('unsupported_tool',`Unknown mutation tool: ${name}`)};
  }
  const affected=findCourse(state,args.courseId)||activeCourse(state);if(affected)affected.updatedAt=now();state.requestLedger[args.requestId]=result;state.requestLedger=Object.fromEntries(Object.entries(state.requestLedger).slice(-200));return{state,result};
}

export function recordLearnerAction(current:LanternState,action:JsonObject){const state=clone(current);state.revision+=1;const course=findCourse(state,action.courseId),lesson=findLesson(course,action.lessonId);if(!course||!lesson)return{result:fail('lesson_not_found','The active lesson was not found.')};
  if(['question','teaching_preference','retry_request'].includes(action.type)){const id=makeId('request');state.requests.unshift({id,courseId:course.id,lessonId:lesson.id,blockId:action.blockId,type:action.type,content:action.content,responseMode:action.responseMode,noteIds:action.noteIds||[],status:'pending',createdAt:now()});logActivity(state,course.id,lesson.id,action.type,`Saved ${action.type.replace('_',' ')} for the next agent turn.`);return{state,result:success(state,'Saved for the learner’s next agent turn.',{learnerRequestId:id})};}
  if(action.type==='note'){const id=makeId('note');state.notes.unshift({id,courseId:course.id,lessonId:lesson.id,blockId:action.blockId,content:action.content,createdAt:now()});logActivity(state,course.id,lesson.id,'note','Learner saved a note.');return{state,result:success(state,'Saved note.',{noteId:id})};}
  if(action.type==='quiz_attempt'){const question=lesson.quiz.find(q=>q.id===action.questionId);if(!question)return{result:fail('request_not_found','Quiz question not found.')};const norm=(v:any)=>Array.isArray(v)?JSON.stringify([...v].sort()):String(v).trim().toLowerCase();const correct=norm(action.answer)===norm(question.correctAnswer),id=makeId('attempt');state.attempts.unshift({id,courseId:course.id,lessonId:lesson.id,questionId:question.id,answer:action.answer,correct,createdAt:now()});logActivity(state,course.id,lesson.id,'quiz_attempt',correct?'Answered a quiz question correctly.':'Quiz answer needs another look.');return{state,result:success(state,correct?'Correct.':'Not yet.',{attemptId:id,correct,explanation:question.explanation,hint:question.hint,attemptsUsed:state.attempts.filter(a=>a.questionId===question.id).length,maxAttempts:question.maxAttempts})};}
  return{result:fail('invalid_component_data','Unsupported learner action.')};}
