/* JSON Schema is intentionally dynamic at this declaration boundary. */
/* eslint-disable @typescript-eslint/no-explicit-any */
type Schema = Record<string, any>;
const str = (maxLength=300, extra:Schema={}) => ({type:'string',minLength:1,maxLength,...extra});
const optStr = (maxLength=300, extra:Schema={}) => ({type:'string',maxLength,...extra});
const arr = (items:Schema,maxItems=50) => ({type:'array',items,maxItems});
const obj = (properties:Schema={},required:string[]=[]) => ({type:'object',properties,required,additionalProperties:false});
const id = str(120,{pattern:'^[A-Za-z0-9][A-Za-z0-9_.:-]*$'});
const read = {readOnlyHint:true};
const mutation = {requestId:id,expectedRevision:{type:'integer',minimum:0}};

const block = obj({id,kind:str(30,{enum:['objective','paragraph','callout','worked_example','definition','steps','comparison','reflection']}),title:optStr(200),body:optStr(5000),data:obj({items:arr(str(1000),30),left:arr(str(1000),20),right:arr(str(1000),20),label:optStr(200)})},['id','kind']);
const diagramNode=obj({id,label:str(200)},['id','label']);
const diagramEdge=obj({from:id,to:id,label:optStr(120)},['from','to']);
const diagramSpec=obj({kind:str(30,{enum:['flow','hierarchy','timeline','cycle','comparison','number_line']}),nodes:arr(diagramNode,40),edges:arr(diagramEdge,80),labels:arr(str(200),40)},['kind','nodes']);
const question=obj({id,type:str(30,{enum:['single_choice','multiple_choice','numeric','ordering']}),prompt:str(1000),options:arr(str(500),12),correctAnswer:{oneOf:[str(1000),{type:'number'},arr(str(500),12)]},hint:str(1000),explanation:str(3000),maxAttempts:{type:'integer',minimum:1,maximum:10},difficulty:optStr(30)},['id','type','prompt','correctAnswer','hint','explanation','maxAttempts']);
const canvasElement=obj({id,type:str(30,{enum:['text','node','connector','formula','callout','image','checkpoint','slider','choice']}),label:optStr(500),body:optStr(2000),unit:optStr(40),min:{type:'number',minimum:-100000,maximum:100000},max:{type:'number',minimum:-100000,maximum:100000},step:{type:'number',exclusiveMinimum:0,maximum:10000},value:{oneOf:[{type:'number'},optStr(1000)]},weight:{type:'number',minimum:-100,maximum:100},color:optStr(20,{pattern:'^#[0-9A-Fa-f]{6}$'}),from:id,to:id,imageUrl:optStr(2000,{format:'uri'}),alt:optStr(1000),options:arr(str(500),12)},['id','type']);
const canvasScene=obj({id,title:str(200),narration:str(4000),focus:optStr(200),durationSeconds:{type:'integer',minimum:5,maximum:600},transition:str(20,{enum:['fade','slide','reveal','focus']}),elements:arr(canvasElement,30)},['id','title','narration','durationSeconds','transition','elements']);
const transcriptCue=obj({id,sceneId:id,speaker:optStr(200),timeLabel:optStr(20),text:str(4000)},['id','sceneId','text']);
const number={type:'number',minimum:-100000,maximum:100000};
const vec3={type:'array',items:number,minItems:3,maxItems:3};
const color=optStr(20,{pattern:'^#[0-9A-Fa-f]{6}$'});
const shaderUniform=obj({name:str(60,{pattern:'^u[A-Za-z0-9_]+$'}),value:number,color},['name']);
const shaderProgram=obj({vertex:optStr(6000),fragment:optStr(6000),intensity:{type:'number',minimum:0,maximum:10},uniforms:arr(shaderUniform,24)});
const threeNode=obj({id,kind:str(30,{enum:['sphere','box','torus','cylinder','cone','plane','icosahedron']}),label:str(200),description:optStr(1000),position:vec3,scale:vec3,rotation:vec3,color,emissive:color,opacity:{type:'number',minimum:0,maximum:1},roughness:{type:'number',minimum:0,maximum:1},metalness:{type:'number',minimum:0,maximum:1},material:str(30,{enum:['standard','wireframe']}),behavior:str(30,{enum:['static','orbit','pulse','spin','float']}),interaction:str(30,{enum:['none','select','value']}),speed:{type:'number',minimum:-10,maximum:10},phase:number,orbitRadius:{type:'number',minimum:.1,maximum:50},value:number,min:number,max:number,step:{type:'number',exclusiveMinimum:0,maximum:10000},unit:optStr(20),weight:{type:'number',minimum:-100,maximum:100},shader:shaderProgram},['id','kind','label','position']);
const threeConnection=obj({id,from:id,to:id,color,pulseSpeed:{type:'number',minimum:0,maximum:20}},['id','from','to']);
const threeCamera=obj({position:vec3,target:vec3,fov:{type:'number',minimum:20,maximum:100}},['position','target']);
const threeEnvironment=obj({background:str(20,{pattern:'^#[0-9A-Fa-f]{6}$'}),fogColor:color,fogDensity:{type:'number',minimum:0,maximum:1},ambientIntensity:{type:'number',minimum:0,maximum:10}},['background']);
const mission=obj({prompt:str(1000),targetRange:{type:'array',items:{type:'number',minimum:0,maximum:100},minItems:2,maxItems:2},successMessage:str(1000)},['prompt','targetRange','successMessage']);
const operation=obj({type:str(30,{enum:['insert_block','update_block','remove_block','update_lesson','set_quiz','add_media']}),block:obj({id,kind:str(30),title:optStr(200),body:optStr(5000),data:obj({url:optStr(2000),alt:optStr(1000),source:optStr(500),transcript:optStr(50000)})},['id','kind']),blockId:id,afterBlockId:id,title:optStr(200),summary:optStr(1000),questions:arr(question,30)},['type']);

export const toolDefinitions = [
  {name:'get_lantern_capabilities',description:'Read the structured lesson components, assessment types, media providers, limits, schema versions, and current WebMCP availability supported by Lantern.',inputSchema:obj(),annotations:read},
  {name:'get_learning_context',description:'Read the active learner, course, outline, lesson, revision, visible semantic location, and unresolved learner requests without scraping the page.',inputSchema:obj({includeLessonBlocks:{type:'boolean'},includeCourseList:{type:'boolean'}}),annotations:read},
  {name:'get_learning_signals',description:'Read course-scoped learner notes, quiz attempts, progress, and recent learning activity.',inputSchema:obj({courseId:id,lessonId:id,sinceRevision:{type:'integer',minimum:0},limit:{type:'integer',minimum:1,maximum:100}}),annotations:read},
  {name:'get_pending_learner_requests',description:'Read questions, teaching preferences, and retry requests saved while no teaching agent turn was active.',inputSchema:obj({courseId:id,lessonId:id,types:arr(str(30,{enum:['question','teaching_preference','retry_request']}),3),limit:{type:'integer',minimum:1,maximum:100}}),annotations:read},
  {name:'list_courses',description:'List the learner’s available courses with progress, recent activity, and active lesson identifiers.',inputSchema:obj({status:str(20,{enum:['active','completed','archived']}),limit:{type:'integer',minimum:1,maximum:100}}),annotations:read},
  {name:'create_course',description:'Create a new runtime course shell from the learner’s goal without overwriting other courses.',inputSchema:obj({title:str(200),goal:str(2000),level:str(50),timeBudgetMinutes:{type:'integer',minimum:5,maximum:100000},learningPreference:str(1000),language:optStr(20),accessibilityPreferences:arr(str(200),20),priorKnowledge:optStr(2000),...mutation},['title','goal','level','timeBudgetMinutes','learningPreference','requestId','expectedRevision'])},
  {name:'update_course_settings',description:'Update selected learner preferences or course goals while preserving the rest of the course.',inputSchema:obj({courseId:id,goal:optStr(2000),level:optStr(50),timeBudgetMinutes:{type:'integer',minimum:5,maximum:100000},learningPreference:optStr(1000),language:optStr(20),reason:str(1000),...mutation},['courseId','reason','requestId','expectedRevision'])},
  {name:'set_course_outline',description:'Create or replace an ordered chapter and lesson plan using stable semantic identifiers.',inputSchema:obj({courseId:id,chapters:arr(obj({id,title:str(200),lessons:arr(obj({id,title:str(200),summary:str(1000),minutes:{type:'integer',minimum:1,maximum:600}},['id','title','summary','minutes']),80)},['id','title','lessons']),30),activeLessonId:id,...mutation},['courseId','chapters','requestId','expectedRevision'])},
  {name:'upsert_lesson_blocks',description:'Write or revise ordered, structured non-media lesson blocks. Use strict attachment tools for all media.',inputSchema:obj({courseId:id,lessonId:id,title:str(200),summary:str(1000),blocks:arr(block,80),mode:str(20,{enum:['replace','append','insert_after']}),afterBlockId:id,...mutation},['courseId','lessonId','title','summary','blocks','mode','requestId','expectedRevision'])},
  {name:'set_lesson_learning_canvas',description:'Create or replace a safe scene-based learning canvas with presentation transitions, interactive primitives, a linked transcript, and whiteboard prompts. This is the primary agent-authoring surface for a lesson; it never accepts arbitrary code.',inputSchema:obj({courseId:id,lessonId:id,id,title:str(200),objective:str(2000),model:str(40,{enum:['none','weighted_sum_probability']}),scenes:{...arr(canvasScene,12),minItems:2},transcriptCues:arr(transcriptCue,60),whiteboardPrompts:arr(str(500),12),...mutation},['courseId','lessonId','id','title','objective','scenes','requestId','expectedRevision'])},
  {name:'set_lesson_3d_experience',description:'Author a real-time Three.js learning world with bounded scene objects, camera controls, animated behaviors, live variables, a game-like mission, connections, and safe loop-free GLSL vertex or fragment shaders. Use this when spatial exploration or simulation materially improves the lesson. Arbitrary JavaScript, HTML, imports, storage, and network access are never accepted.',inputSchema:obj({courseId:id,lessonId:id,id,title:str(200),instructions:str(2000),alt:str(2000),camera:threeCamera,environment:threeEnvironment,nodes:{...arr(threeNode,64),minItems:1},connections:arr(threeConnection,120),outputNodeId:id,mission,afterBlockId:id,...mutation},['courseId','lessonId','id','title','instructions','alt','camera','environment','nodes','requestId','expectedRevision'])},
  {name:'remove_lesson_block',description:'Remove one lesson block by stable identifier and record an undoable change.',inputSchema:obj({courseId:id,lessonId:id,blockId:id,reason:str(1000),...mutation},['courseId','lessonId','blockId','reason','requestId','expectedRevision'])},
  {name:'attach_lesson_image',description:'Attach a real, publicly hosted HTTPS image with accessible alternative text and provenance.',inputSchema:obj({courseId:id,lessonId:id,id,title:str(200),url:str(2000,{format:'uri'}),alt:str(1000),source:str(500),caption:optStr(1000),licenseUrl:optStr(2000,{format:'uri'}),afterBlockId:id,...mutation},['courseId','lessonId','id','title','url','alt','source','requestId','expectedRevision'])},
  {name:'attach_lesson_diagram',description:'Attach a genuine diagram using exactly one public image source or supported structured diagram specification.',inputSchema:{...obj({courseId:id,lessonId:id,id,title:str(200),alt:str(1000),imageUrl:optStr(2000,{format:'uri'}),source:optStr(500),spec:diagramSpec,afterBlockId:id,...mutation},['courseId','lessonId','id','title','alt','requestId','expectedRevision']),oneOf:[{required:['imageUrl','source']},{required:['spec']}] }},
  {name:'attach_lesson_video',description:'Attach a validated, approved video embed with source and accessibility metadata.',inputSchema:obj({courseId:id,lessonId:id,id,title:str(200),url:str(2000,{format:'uri'}),source:str(500),provider:str(30,{enum:['youtube','vimeo']}),caption:optStr(1000),transcript:optStr(50000),startSeconds:{type:'integer',minimum:0},durationSeconds:{type:'integer',minimum:1},thumbnailUrl:optStr(2000,{format:'uri'}),afterBlockId:id,...mutation},['courseId','lessonId','id','title','url','source','provider','requestId','expectedRevision'])},
  {name:'attach_lesson_audio',description:'Attach a high-quality external HTTPS audio recording with a complete transcript.',inputSchema:obj({courseId:id,lessonId:id,id,title:str(200),url:str(2000,{format:'uri'}),transcript:str(50000),source:str(500),durationSeconds:{type:'integer',minimum:1},speaker:optStr(200),afterBlockId:id,...mutation},['courseId','lessonId','id','title','url','transcript','source','requestId','expectedRevision'])},
  {name:'set_lesson_quiz',description:'Create or revise a structured interactive lesson assessment with retry, hint, and explanation contracts.',inputSchema:obj({courseId:id,lessonId:id,questions:arr(question,30),...mutation},['courseId','lessonId','questions','requestId','expectedRevision'])},
  {name:'answer_lesson_question',description:'Answer a pending learner question beside its exact lesson block anchor and mark the request resolved.',inputSchema:obj({requestIdToAnswer:id,answer:str(10000),miniQuiz:question,challenge:optStr(3000),recommendedFollowUp:optStr(1000),...mutation},['requestIdToAnswer','answer','requestId','expectedRevision'])},
  {name:'save_learner_note',description:'Save a learner-authored note from the agent conversation into the shared course state.',inputSchema:obj({courseId:id,lessonId:id,blockId:id,content:str(5000),...mutation},['courseId','lessonId','content','requestId','expectedRevision'])},
  {name:'propose_learning_adaptation',description:'Create a visible, reviewable adaptation proposal grounded in learner signals without applying it.',inputSchema:obj({courseId:id,lessonId:id,signalIds:arr(id,50),reason:str(2000),summary:str(1000),operations:arr(operation,50),...mutation},['courseId','lessonId','signalIds','reason','summary','operations','requestId','expectedRevision'])},
  {name:'apply_learning_adaptation',description:'Apply an accepted adaptation proposal and return an undo change identifier.',inputSchema:obj({adaptationId:id,...mutation},['adaptationId','requestId','expectedRevision'])},
  {name:'undo_agent_change',description:'Undo a reversible agent-authored change when no incompatible later revision prevents it.',inputSchema:obj({changeId:id,reason:str(1000),...mutation},['changeId','reason','requestId','expectedRevision'])},
  {name:'set_lesson_progress',description:'Update lesson status and course progress using verified learner evidence.',inputSchema:obj({courseId:id,lessonId:id,status:str(20,{enum:['not_started','active','completed']}),courseProgress:{type:'number',minimum:0,maximum:100},evidence:arr(id,100),...mutation},['courseId','lessonId','status','courseProgress','requestId','expectedRevision'])},
  {name:'navigate_to_learning_item',description:'Navigate the visible shared workspace to exactly one course, chapter, lesson, block, request, or adaptation identifier without changing progress.',inputSchema:{...obj({courseId:id,chapterId:id,lessonId:id,blockId:id,requestIdToReview:id,adaptationId:id,...mutation},['requestId','expectedRevision']),oneOf:[{required:['courseId']},{required:['chapterId']},{required:['lessonId']},{required:['blockId']},{required:['requestIdToReview']},{required:['adaptationId']}] }},
] as const;

export const toolNames = toolDefinitions.map(tool=>tool.name);
